---
- hosts: all
  become: true
  tasks:

  - name: Install Apache2 package
    ansible.builtin.yum:
      name: httpd
      state: present
      update_cache: yes

  - name: Ensure Apache2 (httpd) is running
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes


