---
- name: Install Docker on all nodes
  hosts: all
  become: yes  # Run tasks with sudo

  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install required dependencies
      yum:
        name: 
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      yum_repository:
        name: docker
        description: Docker Repository
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Install Docker
      yum:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
