---
- hosts: localhost
  tasks:
    - name: download transaction_list
      block: 
        - get_url:
             url: http//apps/l33t.com/transaction_list
             dest: /home/ansible/transaction_list
        - debug: msg="File downloaded successfully"
      rescue:
      
        
   