---
- name: Regular updates on all nodes
  hosts: all
  become: yes

  tasks:
    # Update all packages to the latest version
    - name: Update all packages to the latest version
      yum:
        name: '*'
        state: latest
      register: update_output
      ignore_errors: yes

    - name: Display update output
      debug:
        var: update_output

    # Upgrade all packages
    - name: Upgrade all packages
      command: yum upgrade -y
      register: upgrade_output
      ignore_errors: yes

    - name: Display upgrade output
      debug:
        var: upgrade_output

    # Remove old packages and clean up
    - name: Remove old packages and clean up
      command: yum autoremove -y
      register: autoremove_output
      ignore_errors: yes

    - name: Display autoremove output
      debug:
        var: autoremove_output

    # Clean all cached files
    - name: Clean all cached files
      command: yum clean all
      register: clean_output
      ignore_errors: yes

    - name: Display clean output
      debug:
        var: clean_output

